version: "3"
services:

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./php/www:/www
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php
    php:
        container_name: php-fpm
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./php/www:/www
        links:
            - mongo
        ports:
            - "9000:9000"

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
